https:www.simonmtswenism@gmail.com

name:.dotnet.yml#//(simonMtsweni).
#SimonMtsweni#.
-
  push:https://www.github.com/simonMtsweni/-SimonMtsweni..git
    branches:-"SimonMtsweni." 
  pull_request:https://www.gmail.com
    branches:(simon Mtsweni)

jobs:**
  build:_-

    runs-on:UI/X

    steps:--
    - uses:actions/checkout@_simonMtsweni.0.1.0
    - name:Setup.N.E.T://()
      uses:actions/setup-dotnet@0.4.0//
      with:--
        dotnet-version:4.0.x
    - name:Restore;'A-Zdependencies
      run:dotnet-restore
    - name:..
      run:.dotnet.build --no-restore
    - name:Test:..
      run:N.E.T.dotnet_-test'--no-build'--verbosity normal..
